/**
 * IDEA: Contacts with VCF import/export support (node-vcf).
 * IDEA: Guided tour (react-joyride).
 *
 * TODO: Implement translations (i18next, react-i18next, moment-timezone).
 * TODO: Implement balance tracking of individual addresses and accounts.
 * NOTE: RPC getbalance returns incorrect account balances after using RPC sendtoaddress. They're ok if only RPC sendmany is used on a fresh wallet.
 *       - Affects: ADDRESS_BOOK, TRANSACTIONS, TRANSACTION_, SEND_
 *
 * A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
 */
export const ADDRESS_BOOK = 'ADDRESS_BOOK'
export const ADDRESS_BOOK_SET_SHOW_ACCOUNT = 'ADDRESS_BOOK_SET_SHOW_ACCOUNT'
export const ADDRESS_NEW_SET_ACCOUNT = 'ADDRESS_NEW_SET_ACCOUNT'
export const ADDRESS_NEW_SET_ERROR = 'ADDRESS_NEW_SET_ERROR'
export const ADDRESS_NEW_TOGGLE_DIALOG = 'ADDRESS_NEW_TOGGLE_DIALOG'
export const ADDRESS_NEW_TOGGLE_SNACKBAR = 'ADDRESS_NEW_TOGGLE_SNACKBAR'
export const BITCOINAVERAGE_REQUEST = 'BITCOINAVERAGE_REQUEST'
export const BITCOINAVERAGE_RESPONSE = 'BITCOINAVERAGE_RESPONSE'
export const BITTREX_REQUEST = 'BITTREX_REQUEST'
export const BITTREX_RESPONSE = 'BITTREX_RESPONSE'
export const CHAINBLENDER_INFO = 'CHAINBLENDER_INFO'
export const CHAINBLENDER_TOGGLE = 'CHAINBLENDER_TOGGLE'
export const CURRENCY_CONVERTER = 'CURRENCY_CONVERTER'
export const CURRENCY_CONVERTER_CLEAR = 'CURRENCY_CONVERTER_CLEAR'
export const INCENTIVE_INFO = 'INCENTIVE_INFO'
export const KEY_IMPORT_BUTTON_CHECK = 'KEY_IMPORT_BUTTON_CHECK'
export const KEY_IMPORT_SET_ACCOUNT = 'KEY_IMPORT_SET_ACCOUNT'
export const KEY_IMPORT_SET_ERROR = 'KEY_IMPORT_SET_ERROR'
export const KEY_IMPORT_SET_KEY = 'KEY_IMPORT_SET_KEY'
export const KEY_IMPORT_TOGGLE_DIALOG = 'KEY_IMPORT_TOGGLE_DIALOG'
export const KEY_IMPORT_TOGGLE_SNACKBAR = 'KEY_IMPORT_TOGGLE_SNACKBAR'
export const MENU_TOGGLE_DRAWER = 'MENU_TOGGLE_DRAWER'
export const NETWORK_INFO = 'NETWORK_INFO'
export const POLONIEX_CLOSED = 'POLONIEX_CLOSED'
export const POLONIEX_OPEN = 'POLONIEX_OPEN'
export const POLONIEX_REQUEST = 'POLONIEX_REQUEST'
export const POLONIEX_TICKER = 'POLONIEX_TICKER'
export const REWARD_CALCULATOR = 'REWARD_CALCULATOR'
export const REWARD_CALCULATOR_CLEAR = 'REWARD_CALCULATOR_CLEAR'
export const SEND_RECIPIENT_NEW = 'SEND_RECIPIENT_NEW'
export const SEND_RECIPIENT_REMOVE = 'SEND_RECIPIENT_REMOVE'
export const SEND_RECIPIENT_SET = 'SEND_RECIPIENT_SET'
export const SEND_SET_ACCOUNT = 'SEND_SET_ACCOUNT'
export const SEND_SET_ERROR = 'SEND_SET_ERROR'
export const SEND_TOGGLE_BUTTON = 'SEND_TOGGLE_BUTTON'
export const SEND_TOGGLE_DRAWER = 'SEND_TOGGLE_DRAWER'
export const SEND_VERIFY = 'SEND_VERIFY'
export const SET_LOCAL_CURRENCY = 'SET_LOCAL_CURRENCY'
export const TRANSACTION_LOOKUP = 'TRANSACTION_LOOKUP'
export const TRANSACTION_TOGGLE_DIALOG = 'TRANSACTION_TOGGLE_DIALOG'
export const TRANSACTIONS = 'TRANSACTIONS'
export const TRANSACTIONS_SET_FILTER_BY = 'TRANSACTIONS_SET_FILTER_BY'
export const TRANSACTIONS_SET_SHOW_CATEGORY = 'TRANSACTIONS_SET_SHOW_CATEGORY'
export const TRANSACTIONS_SET_SHOW_SINCE = 'TRANSACTIONS_SET_SHOW_SINCE'
export const WALLET_DAEMON = 'WALLET_DAEMON'
export const WALLET_ENCRYPT = 'WALLET_ENCRYPT'
export const WALLET_ENCRYPT_SET_ERROR = 'WALLET_ENCRYPT_SET_ERROR'
export const WALLET_ENCRYPT_SET_PASSPHRASE = 'WALLET_ENCRYPT_SET_PASSPHRASE'
export const WALLET_ENCRYPT_SET_REPEAT = 'WALLET_ENCRYPT_SET_REPEAT'
export const WALLET_ENCRYPT_TOGGLE_DIALOG = 'WALLET_ENCRYPT_TOGGLE_DIALOG'
export const WALLET_ENCRYPT_TOGGLE_SNACKBAR = 'WALLET_ENCRYPT_TOGGLE_SNACKBAR'
export const WALLET_INFO = 'WALLET_INFO'
export const WALLET_LOCK = 'WALLET_LOCK'
export const WALLET_LOCK_CHECK = 'WALLET_LOCK_CHECK'
export const WALLET_LOCK_TOGGLE_SNACKBAR = 'WALLET_LOCK_TOGGLE_SNACKBAR'
export const WALLET_UNLOCK = 'WALLET_UNLOCK'
export const WALLET_UNLOCK_SET_ERROR = 'WALLET_UNLOCK_SET_ERROR'
export const WALLET_UNLOCK_SET_PASSPHRASE = 'WALLET_UNLOCK_SET_PASSPHRASE'
export const WALLET_UNLOCK_TOGGLE_DIALOG = 'WALLET_UNLOCK_TOGGLE_DIALOG'
export const WALLET_UNLOCK_TOGGLE_SNACKBAR = 'WALLET_UNLOCK_TOGGLE_SNACKBAR'
export const WATCHONLY_ADD = 'WATCHONLY_ADD'
export const WATCHONLY_ADD_SET_ADDRESS = 'WATCHONLY_ADD_SET_ADDRESS'
export const WATCHONLY_ADD_SET_ERROR = 'WATCHONLY_ADD_SET_ERROR'
export const WATCHONLY_ADD_SET_NOTE = 'WATCHONLY_ADD_SET_NOTE'
export const WATCHONLY_ADD_TOGGLE_DIALOG = 'WATCHONLY_ADD_TOGGLE_DIALOG'
export const WATCHONLY_ADD_TOGGLE_SNACKBAR = 'WATCHONLY_ADD_TOGGLE_SNACKBAR'
export const WATCHONLY_EDIT = 'WATCHONLY_EDIT'
export const WATCHONLY_EXPLORER_LOOKUP = 'WATCHONLY_EXPLORER_LOOKUP'
export const WATCHONLY_REMOVE = 'WATCHONLY_REMOVE'
export const WATCHONLY_VIEW_ADDRESS = 'WATCHONLY_VIEW_ADDRESS'
export const WATCHONLY_VIEW_TOGGLE_DIALOG = 'WATCHONLY_VIEW_TOGGLE_DIALOG'

/**
 * TODO: Implement key dump.
 * TODO: Implement wallet dump.
 * TODO: Implement wallet backup.
 * TODO: Implement wallet check.
 * TODO: Implement wallet repair.
 * TODO: Implement wallet passphrase change.
 */
export const KEY_DUMP = 'KEY_DUMP'
export const KEY_DUMP_SET_ADDRESS = 'KEY_DUMP_SET_ADDRESS'
export const KEY_DUMP_SET_ERROR = 'KEY_DUMP_SET_ERROR'
export const KEY_DUMP_TOGGLE_DIALOG = 'KEY_DUMP_TOGGLE_DIALOG'
export const WALLET_DUMP = 'WALLET_DUMP'
export const WALLET_DUMP_TOGGLE_DIALOG = 'WALLET_DUMP_TOGGLE_DIALOG'
export const WALLET_DUMP_TOGGLE_SNACKBAR = 'WALLET_DUMP_TOGGLE_SNACKBAR'
export const WALLET_BACKUP = 'WALLET_BACKUP'
export const WALLET_CHECK = 'WALLET_CHECK'
export const WALLET_REPAIR = 'WALLET_REPAIR'
export const WALLET_PASSPHRASE_CHANGE = 'WALLET_PASSPHRASE_CHANGE'
